/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class calculadorajni_Aritmetica */

#ifndef _Included_calculadorajni_Aritmetica
#define _Included_calculadorajni_Aritmetica
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     calculadorajni_Aritmetica
 * Method:    suma
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_calculadorajni_Aritmetica_suma
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     calculadorajni_Aritmetica
 * Method:    resta
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_calculadorajni_Aritmetica_resta
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     calculadorajni_Aritmetica
 * Method:    mul
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_calculadorajni_Aritmetica_mul
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     calculadorajni_Aritmetica
 * Method:    div
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_calculadorajni_Aritmetica_div
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
